### ISSUE TITLE
Is it complete?

### ISSUE THREAD

**Issue by pedluis** [Traxlead/googlecustomerreviewssnippet#1]
Hello guys, i've tried to use this module but it does not work. Is it normal because the module is not complete? or there is a problem with my prestashop?

Regards

**Comment by albangonzalez** [comment]
Hi @pedluis, the module is complete. It should work fine with you PrestaShop if you are using at least the version 1.6. Can you tell me what is yours ?
Sometimes the payment module doesn't redirect to the confirmation page and use its proper one without including necessary hooks.

By the way: you MUST use HTTPS (https://support.google.com/merchants/answer/7106244)

**Comment by syntaxisarg** [comment]
Hi @albangonzalez , when I try to install the module, it does not appear in the list. My version is 1.6.1

**Comment by albangonzalez** [comment]
Hi @syntaxisarg be sure to type "Google Customers Reviews" while the filter is set on "Installed and uninstalled modules"

**Comment by syntaxisarg** [comment]
Sorry for the inconvenience, it's already working.
The module does not show the Badge?

**Comment by albangonzalez** [comment]
Sorry mate, it doesn't show the badge. It only shows the Google popup when the confirmation page is displayed. But if you can wait until monday I'll add the badge ;-)

**Comment by syntaxisarg** [comment]
Of course I can wait!
Similarly, it would not be working since the pop-up window does not appear on the confirmation page. I have to do more tests.
The delivery date variable as it is handled?
